### ISSUE TITLE
README docs error : `Ratelimit` should be `MultiRegionRatelimit `

### ISSUE THREAD

**Issue by grempe** [upstash/ratelimit#16]
In the README example for multiregion setup.

https://github.com/upstash/ratelimit#multiregion-replicated-ratelimiting

The `limiter` config should be:

```typescript
limiter: MultiRegionRatelimit.slidingWindow(10, '10 s'),
```

instead of what it currently shows which results in a TypeScript type error:

```typescript
limiter: Ratelimit.slidingWindow(10, '10 s'),
```

**Comment by chronark** [comment]
@grempe Thank you.

**Comment by grempe** [comment]
@chronark : You win the speediest bug fix resolution award for the Internet today. 🏆
