### ISSUE TITLE
Next Middleware new signature

### ISSUE THREAD

**Issue by csulit** [upstash/ratelimit#19]
I'm getting this error 

error - node_modules/next/dist/server/web/spec-extension/response.js (18:0) @ handleMiddlewareField
error - The middleware "/src/middleware" accepts an async API directly with the form:
  
```
export function middleware(request, event) {
    return NextResponse.redirect('/new-location')
}
```
  
Read more: https://nextjs.org/docs/messages/middleware-new-signature
  
But changing `NextResponse.next(request)` -> `NextResponse.next()` and `NextResponse.rewrite(new URL("/api/blocked", request.url), request)` -> `NextResponse.rewrite(new URL("/api/blocked", request.url))` fixed the error.

**Comment by chronark** [comment]
Hey @csulit can you share a code snippet where this happens?
Thank you!

**Comment by chronark** [comment]
Or is this about an example being broken?

**Comment by csulit** [comment]
@chronark The example is not working with next version 13.0.7

**Comment by chronark** [comment]
ok thank you, I'll fix that
