### ISSUE TITLE
middleware.ts env - using UPSTASH_REDIS_REST_URL with "https://" blocks entry, using without blocks analytics

### ISSUE THREAD

**Issue by jpwogaman** [upstash/ratelimit#28]
I am trying to setup the [middleware.ts](https://github.com/upstash/ratelimit/blob/main/examples/nextjs/middleware.ts) example for my Next.js application to allow for easy ratelimiting and DDoS protection.

When I use the following for my environment variables:

```env
UPSTASH_REDIS_REST_URL="https://example.upstash.io"
```
I get the following error:

```cli
error - node_modules\@upstash\redis\esm\pkg\http.js (101:0) @ HttpClient.request
error - Unauthorized
null
```

When I take the "https://" out:
```env
UPSTASH_REDIS_REST_URL="example.upstash.io"
```

The first error goes away, and my app works as expected. But, I get the following error:

```cli
event - compiled successfully in 32 ms (154 modules)
Failed to record analytics [TypeError: Failed to parse URL from example.upstash.io]
```

**Comment by jpwogaman** [comment]
UPDATE: I get the same error even if I do not have analytics enabled in middleware.ts

```ts
const ratelimit = new Ratelimit({
  redis: Redis.fromEnv(),
  limiter: Ratelimit.cachedFixedWindow(20, '10 s'),
  ephemeralCache: new Map()

  //   cannot be commented out, must be declared false or error will occur:
  //   analytics: true
  //   analytics: false
})
```

**Comment by chronark** [comment]
you also need to provide `UPSTASH_REDIS_REST_TOKEN`, you got an authorization error, so I assume you forgot it

checking out the type error. it should be optional

**Comment by chronark** [comment]
Can you provide the error message for the type, it is defined as optional and setting it undefined works for me

**Comment by jpwogaman** [comment]
I just left out the UPSTASH_REDIS_REST_TOKEN for the sake of this example, but I am using it. 

I don't want to leave analytics as undefined, I want to use the analytics. The error I detailed above is not a type error, it is coming from the terminal.

**Comment by jpwogaman** [comment]
you're correct, I was using the password as the token.

```env
# from Upstash dashboard under REST API
# if you don't click the little view button or copy button, it looks a bit misleading.  

UPSTASH_REDIS_REST_TOKEN="********"
```
