### ISSUE TITLE
Documentation is not found.

### ISSUE THREAD

**Issue by hyunbinseo** [upstash/ratelimit#35]
> 404 - Not Found
> This file or directory could not be found.

https://doc.deno.land/https://deno.land/x/upstash_ratelimit/src/mod.ts
https://deno.land/x/upstash_ratelimit/src/mod.ts

**Comment by chronark** [comment]
https://deno.land/x/upstash_ratelimit@v0.4.0/packages/sdk/src/index.ts

I'll update the links, thank you
