### ISSUE TITLE
QStash integration

### ISSUE THREAD

**Issue by guy-borderless** [upstash/ratelimit#42]
It would be cool if I could associate rate limits to endpoints in the qstash UI and not have to change my code

**Comment by chronark** [comment]
Can you share a bit more how you would like to use this?
Like what would it look like from a user perspective and what problem does it solve?

**Comment by guy-borderless** [comment]
My worker encapsulates a resource that has a throttling constraint and concurrency constraint (which changes every once in a while). Multiple endpoints send this worker messages. Since everything runs through your queue(👌) it would be nice if I could just attach the rate/concurrency limits to the endpoint and have the queue take care of delivering messages according to the throttling & concurrency constraints. This saves me 
1. writing some infra code and
2. delivering failed responses due to an expected scenario

**Comment by chronark** [comment]
Ah ok, so you want per endpoint ratelimiting in qstash and it's not really related to @upstash/ratelimit, right?

**Comment by guy-borderless** [comment]
I'll use @upstash/ratelimit didn't find a better repo
