### ISSUE TITLE
Is there a way to fetch the remaining requests for a given key 

### ISSUE THREAD

**Issue by norberto-e-888** [upstash/ratelimit#56]
I have a use case where I am going to be calling `RateLimiter.limit` using userId's, and I need to display to the user how many requests they have left.

**Comment by mcky** [comment]
+1, we have a similar issue. We want to show users their rate limit as it renews (with sliding window), but can currently only decremenet their allowance

**Comment by mahendraHegde** [comment]
did you check `remaining` from `RatelimitResponse`?
```
const { success,remaining } = await ratelimit.limit(identifier);
```

**Comment by off99555** [comment]
> did you check `remaining` from `RatelimitResponse`?
> 
> ```
> const { success,remaining } = await ratelimit.limit(identifier);
> ```

That would cause the increment in number of usages. We only want to read remaining without modifying the data.
