### ISSUE TITLE
Dynamic token cost on Ratelimit.tokenBucket algorithm

### ISSUE THREAD

**Issue by norberto-e-888** [upstash/ratelimit#58]
Is there a way to dynamically calculate how many tokens a request should cost?

**Comment by chronark** [comment]
Check this script: https://github.com/upstash/ratelimit/blob/c509628a6c1490121d810822ce7c880ddb02c44c/packages/sdk/src/single.ts#L284

It's either 3 or 4, depending on whether the bucket exists and its state
