### ISSUE TITLE
Limiting Concurrency

### ISSUE THREAD

**Issue by bkniffler** [upstash/ratelimit#71]
Thanks for this library! Would it be hard to add limitting concurrency? Would love to use this library with upstash redis to limit API calls, but a few APIs incur concurrency/parallelity limitations. Currently using bottleneck.

**Comment by ogzhanolguncu** [comment]
Could you please give some more details about what you are trying to achieve?

**Comment by bkniffler** [comment]
Lets say I want to call API a, which has these limitations:
- 100 requests per minute
- 2 concurrent requests max at the same time

Here is an example with Bottleneck:
```ts
const limiter = new Bottleneck({
  reservoir: 100, // initial value
  reservoirRefreshAmount: 100,
  reservoirRefreshInterval: 60 * 1000,
  maxConcurrent: 2,
});
```

With upstash ratelimit:
```ts
const ratelimit = new Ratelimit({
  redis: Redis.fromEnv(),
  limiter: Ratelimit.slidingWindow(100, "60 s"),
});
```

But we're missing the concurrency part to limit this to 2 maximum requests in parallel.

**Comment by ogzhanolguncu** [comment]
I believe, without locking we can't achieve that right now. We are about to release a distributed lock soon. Maybe we can couple it with this and allow users to limit the concurrent access.

**Comment by bkniffler** [comment]
Thanks @ogzhanolguncu, Sounds cool, is there any info about the distributed lock already?

**Comment by ogzhanolguncu** [comment]
We released it yesterday, here you go. https://github.com/upstash/lock

**Comment by ogzhanolguncu** [comment]
bump

**Comment by bkniffler** [comment]
I've just tried to use the ratelimitter of up stash again. lock doesn't really help because it neither allows to wait for until the lock is resolved nor does it allow to set a concurrency @ogzhanolguncu :(

**Comment by ogzhanolguncu** [comment]
We are planning to add a native support for concurrency pretty soon.

**Comment by bkniffler** [comment]
Great, would love to be pinged. I've implemented Bottleneck for now. Happy to switch to ratelimit-js once concurrency works well.
