### ISSUE TITLE
custom rates support

### ISSUE THREAD

**Issue by enesakar** [upstash/ratelimit#75]
in the ratelimit sdk, is there a way consume with different rates? e.g. in openai api, I will allow 100 words per hour so I need to count the words in the prompt and consume it. so something like:
ratelimit.limit(identifier, wordCount)

**Comment by ogzhanolguncu** [comment]
bump

**Comment by sourabpramanik** [comment]
@enesakar  I was able to create this feature, I only did it for fixed window for now and I tested it as well it works fine.  But I want to know how many such rates can we expect from a user, I mean a user can add only one extra rate(like you have mentioned) or there can be many of them?

**Comment by ogzhanolguncu** [comment]
I feel like I still don't understand the practicality of this. What problem are we exactly trying to solve? @sourabpramanik, can you walk me through your example case so I can have a better understanding of the situation?

**Comment by enesakar** [comment]
In AI APIs the quotas are per token not per request. I need to limit the rate by token count. so each request has different token/weight. currently this is not possible as each request is `one`.

**Comment by sourabpramanik** [comment]
Sure, so we are already rate-limiting based on only one factor that is per request. Now we want to have some custom limiters like for example word counts. So these custom limiters can be of any type, having different rates, limits, and as many as the user wants to have. So I have modified the fixed window algorithm for now such that it can work for these cases. If you want I can raise a PR so you may understand better

**Comment by sourabpramanik** [comment]
Sorry for the delay, @enesakar @ogzhanolguncu please review the PR and give your feedback.

**Comment by off99555** [comment]
A good use case for this feature is for subtracting credits from a user's account. Currently the `limit` function always subtract 1 credit from the account. 
@sourabpramanik Is it possible for the API to simply ask for number (e.g. credits) to subtract?
That would be the cleanest API for me. You might want to subtract 1.2 credits sometimes, or sometimes 0.5, or sometimes 10.

**Comment by sourabpramanik** [comment]
> A good use case for this feature is for subtracting credits from a user's account. Currently the `limit` function always subtract 1 credit from the account. @sourabpramanik Looking at the API proposal above, I think it's a bit complicated. Is it possible for the API to simply ask for number (e.g. credits) to subtract? That would be the cleanest API for me. You might want to subtract 1.2 credits sometimes, or sometimes 0.5, or sometimes 10.

Hey @off99555 by credits do you mean tokens? If yes then when you init the RateLimit you need to specify the max tokens and the limit function call will subtract tokens which can be dynamic and not necessarily be one credit, but yes I have to check the case of floating tokens maybe rounding off will be much better. I hope I got you right

**Comment by off99555** [comment]
@sourabpramanik Can the API be like this? I think we just need a number and no words.
```js
const { success, limit, remaining, reset } = await ratelimit.limit(
    ip ?? "anonymous",
    undefined,
    20, // a custom deduction
  );
```

**Comment by sourabpramanik** [comment]
Yes, we can create two variants, one variant is for implementing one custom rate without any identifier since there is only one custom rate just like you mentioned, and another variant will be for multiple custom rates which will need identifiers because we need to track the token for exhausting. What do you think?

**Comment by sourabpramanik** [comment]
I think having multiple custom rates is very expensive because for every request we have to run a loop to execute the script to reduce the token before any one of them has exhausted.

**Comment by ogzhanolguncu** [comment]
I believe we should avoid overcomplicating the API. The initial implementation proposal was fine. And, let's add a more concrete example to ensure we all have a unified understanding. Preferably, using OpenAI with chat completion or embeddings creation.

**Comment by sourabpramanik** [comment]
Yes I agree I will rework on the api and let you all know

**Comment by ogzhanolguncu** [comment]
@off99555 I like the idea. Yeah, users definitely should be able to pick their own subtraction rates.

**Comment by sourabpramanik** [comment]
@ogzhanolguncu @off99555 I have updated to API and the example app. Can you guys please check if this works so then I can implement the same logic in the rest of the algorithms and multi-region algorithms.

**Comment by enesakar** [comment]
@sourabpramanik, can you please share how the end user API will change? Perhaps you can commit the new README so we can easily see the new user API. 

This is a must-have feature for AI applications (due to tokens), so your effort is greatly appreciated!

**Comment by sourabpramanik** [comment]
> @sourabpramanik, can you please share how the end user API will change? Perhaps you can commit the new README so we can easily see the new user API. 
> 
> This is a must-have feature for AI applications (due to tokens), so your effort is greatly appreciated!

Yes definitely I will do that

**Comment by sourabpramanik** [comment]
@enesakar as mentioned I have added a small [doc](https://github.com/upstash/ratelimit/blob/6bae65da88b5b7d6a810614c664987a70a52e962/CUSTOM_RATE.md) on the change the API will have

**Comment by enesakar** [comment]
@sourabpramanik I added a comment.
