### ISSUE TITLE
How to set one hour limit for sliding window?

### ISSUE THREAD

**Issue by samuelpalaciosdev** [upstash/ratelimit#85]
Hey, I've been trying to setup my rate limiter like this:
`const ratelimit = new Ratelimit({ redis: Redis.fromEnv(),
 limiter: Ratelimit.slidingWindow(2, '3600 s'), }); `
But it doesn't seem to work, there's a special way to reference an hour or theres a time limit?

**Comment by fahreddinozcan** [comment]
Hey, can you try `slidingWindow(2, "1 h")`? The possible units are `ms | s | m | h | d |`

**Comment by samuelpalaciosdev** [comment]
Thanks! didn't know that. It could be a good add to the documentation

**Comment by samuelpalaciosdev** [comment]
Thanks! didn't know that. It could be a good add to the documentation.
