### ISSUE TITLE
No TTL set for slidingWindow rate limit keys on latest version

### ISSUE THREAD

**Issue by szwabodev** [upstash/ratelimit#95]
Hello,

I noticed that all of the keys stored in redis remain kept forever since I upgraded to latest version of **@upstash/ratelimit** (**1.0.3** to be specific). I use **slidingWindow** method for rate limiting, and after reverting to version 1.0.1 everything works fine and TTL is set for every key created by Ratelimit. I don't use analytics if this matters (it's set to false).

Hopefully you can take a look and have it fixed, for now I must remain on the older version.

**Comment by CahidArda** [comment]
Hello there,

I noticed the same issue in regular sliding window and I have a fix in PR #94. I am assuming you are using that one. This PR will fix the issue for regular rate limiting. If you are experiencing this is Multi Region sliding window, let me know!

**Comment by CahidArda** [comment]
hi @szwabodev,

The PR fixing this issue was merged. We have a new version 1.1.1
